# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run NUnit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install playwright dependencies
      run: pwsh ./NUnitPlaywrightFramework/bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Use Secrets
      run: |
        echo "export USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
        echo "export PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        echo "export HEADLESS=${{ vars.HEADLESS }}" >> $GITHUB_ENV
      shell: bash
    - name: Test
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        HEADLESS: ${{ vars.HEADLESS }}
      run: dotnet test --no-build --verbosity normal
